### ISSUE TITLE
auto item pickup

### ISSUE THREAD

**Issue by JsonTextfield** [ClaytonMoutzouris/Gamble-v2.0#3]
We need item pickup to be automatic instead of with the down button

**Comment by ClaytonMoutzouris** [comment]
This issue has been fixed in the latest update to the master stream. My current fix for this is to give item prototypes an "autoPickup" flag, so that certain items can be picked up automatically (health items, quest items, keys, and crystals). This decision was made based on feedback from multiple testers.
